### ISSUE TITLE
Pickle error when running aer_video and aer_blink_detect

### ISSUE THREAD

**Issue by Seanny123** [AndreaCensi/env_dvs#3]
When I run aer_video I get the following error:

```
WARNING:quickapp:No description at all for <class 'aer.programs.video.app.AERVideoApp'>
/home/sean/CNRG/env_dvs-master/src/quickapp/src/decent_params/decent_params_imp.py:138: UserWarning: Not sure below
  warnings.warn('Not sure below')
WARNING:video:PyContracts disabled for speed. Use --contracts to activate.
INFO:contracts:All contracts checking disabled.
/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app.py:112: UserWarning: removed configuration below
  warnings.warn('removed configuration below')  # (start)
quickapp using db tmp-videos/tmp/compmake
/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/compmake_context.py:187: UserWarning: add prefix to report manager
  warnings.warn('add prefix to report manager')
ERROR:compmake:Cannot set key cm:default:job:aereventsshowsimple-exampledata/censi.mit.edu/pub/1212DVSdata/data/dec10/flying/l11.aedat-0.03-aer_video_meat: cannot pickle object of class Job: [Errno 36] File name too long: 'tmp-videos/tmp/compmake/cm:default:job:aereventsshowsimple-exampledataCMSLASHcensi.mit.eduCMSLASHpubCMSLASH1212DVSdataCMSLASHdataCMSLASHdec10CMSLASHflyingCMSLASHl11.aedat-0.03-aer_video_meat.pickle.gz.tmp'
ERROR:compmake:[Errno 36] File name too long: 'tmp-videos/tmp/compmake/cm:default:job:aereventsshowsimple-exampledataCMSLASHcensi.mit.eduCMSLASHpubCMSLASH1212DVSdataCMSLASHdataCMSLASHdec10CMSLASHflyingCMSLASHl11.aedat-0.03-aer_video_meat.pickle.gz.tmp'
Traceback (most recent call last):
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/storage/filesystem.py", line 75, in __setitem__
    safe_pickle_dump(value, filename, protocol)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/safe_pickle.py", line 10, in safe_pickle_dump
    with safe_write(filename, **safe_write_options) as f:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/safe_write.py", line 23, in safe_write
    with fopen(tmp_filename, mode) as f:
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/safe_write.py", line 19, in <lambda>
    compresslevel=compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 36] File name too long: 'tmp-videos/tmp/compmake/cm:default:job:aereventsshowsimple-exampledataCMSLASHcensi.mit.eduCMSLASHpubCMSLASH1212DVSdataCMSLASHdataCMSLASHdec10CMSLASHflyingCMSLASHl11.aedat-0.03-aer_video_meat.pickle.gz.tmp'
INFO:compmake:Strange! I could not reproduce the pickling error for the object of class Job
ERROR:quickapp:Traceback (most recent call last):
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/decent_params/utils/script_utils.py", line 49, in wrap_script_entry_point_noexit
    ret = function(args)
  File "<string>", line 2, in main
  File "build/bdist.linux-x86_64/egg/contracts/main.py", line 296, in contracts_checker
    result = function_(*args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app_base.py", line 151, in main
    ret = self.go()
  File "<string>", line 2, in go
  File "build/bdist.linux-x86_64/egg/contracts/main.py", line 296, in contracts_checker
    result = function_(*args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app.py", line 128, in go
    self.define_jobs_context(context)
  File "/home/sean/CNRG/env_dvs-master/src/rcl/src/aer/programs/video/app.py", line 28, in define_jobs_context
    c.comp(aer_video_meat, log=log, interval=interval, model=model)
  File "<string>", line 2, in comp
  File "build/bdist.linux-x86_64/egg/contracts/main.py", line 271, in contracts_checker
    return function_(*args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/compmake_context.py", line 99, in comp
    promise = Context.comp(self, f, *args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/context.py", line 65, in comp
    return comp_(self, command_, *args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/ui/ui.py", line 319, in comp_
    set_job(job_id, c, db=db)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/jobs/storage.py", line 77, in set_job
    db[key] = computation
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/time_track.py", line 55, in wrapper
    return f(self, *args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/storage/filesystem.py", line 89, in __setitem__
    emsg = find_pickling_error(value)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/debug_pickler.py", line 31, in find_pickling_error
    raise Exception(msg)
Exception: I could not find the exact pickling error.

```

When I run aer_blink_detect I get a similar error:

```
/home/sean/CNRG/env_dvs-master/src/quickapp/src/decent_params/decent_params_imp.py:138: UserWarning: Not sure below
  warnings.warn('Not sure below')
WARNING:aer_blink_detect:PyContracts disabled for speed. Use --contracts to activate.
INFO:contracts:All contracts checking disabled.
/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app.py:112: UserWarning: removed configuration below
  warnings.warn('removed configuration below')  # (start)
quickapp using db l2/compmake
/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/compmake_context.py:187: UserWarning: add prefix to report manager
  warnings.warn('add prefix to report manager')
INFO:compmake:Creating basepath 'l2/compmake'
ERROR:compmake:Cannot set key cm:default:job:exampledata/censi.mit.edu/pub/1212DVSdata/data/dec10/flying/l2.aedat-aer_blink_detect: cannot pickle object of class Job: [Errno 36] File name too long: 'l2/compmake/cm:default:job:exampledataCMSLASHcensi.mit.eduCMSLASHpubCMSLASH1212DVSdataCMSLASHdataCMSLASHdec10CMSLASHflyingCMSLASHl2.aedat-aer_blink_detect.pickle.gz.tmp'
ERROR:compmake:[Errno 36] File name too long: 'l2/compmake/cm:default:job:exampledataCMSLASHcensi.mit.eduCMSLASHpubCMSLASH1212DVSdataCMSLASHdataCMSLASHdec10CMSLASHflyingCMSLASHl2.aedat-aer_blink_detect.pickle.gz.tmp'
Traceback (most recent call last):
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/storage/filesystem.py", line 75, in __setitem__
    safe_pickle_dump(value, filename, protocol)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/safe_pickle.py", line 10, in safe_pickle_dump
    with safe_write(filename, **safe_write_options) as f:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/safe_write.py", line 23, in safe_write
    with fopen(tmp_filename, mode) as f:
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/safe_write.py", line 19, in <lambda>
    compresslevel=compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 34, in open
    return GzipFile(filename, mode, compresslevel)
  File "/usr/lib/python2.7/gzip.py", line 94, in __init__
    fileobj = self.myfileobj = __builtin__.open(filename, mode or 'rb')
IOError: [Errno 36] File name too long: 'l2/compmake/cm:default:job:exampledataCMSLASHcensi.mit.eduCMSLASHpubCMSLASH1212DVSdataCMSLASHdataCMSLASHdec10CMSLASHflyingCMSLASHl2.aedat-aer_blink_detect.pickle.gz.tmp'
INFO:compmake:Strange! I could not reproduce the pickling error for the object of class Job
ERROR:quickapp:Traceback (most recent call last):
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/decent_params/utils/script_utils.py", line 49, in wrap_script_entry_point_noexit
    ret = function(args)
  File "<string>", line 2, in main
  File "build/bdist.linux-x86_64/egg/contracts/main.py", line 296, in contracts_checker
    result = function_(*args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app_base.py", line 151, in main
    ret = self.go()
  File "<string>", line 2, in go
  File "build/bdist.linux-x86_64/egg/contracts/main.py", line 296, in contracts_checker
    result = function_(*args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app.py", line 128, in go
    self.define_jobs_context(context)
  File "/home/sean/CNRG/env_dvs-master/src/rcl/src/aer/programs/blink_detect/rcl_detect_app.py", line 50, in define_jobs_context
    write_png=options.video)
  File "<string>", line 2, in comp
  File "build/bdist.linux-x86_64/egg/contracts/main.py", line 271, in contracts_checker
    return function_(*args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/compmake_context.py", line 99, in comp
    promise = Context.comp(self, f, *args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/context.py", line 65, in comp
    return comp_(self, command_, *args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/ui/ui.py", line 319, in comp_
    set_job(job_id, c, db=db)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/jobs/storage.py", line 77, in set_job
    db[key] = computation
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/time_track.py", line 55, in wrapper
    return f(self, *args, **kwargs)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/storage/filesystem.py", line 89, in __setitem__
    emsg = find_pickling_error(value)
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/utils/debug_pickler.py", line 31, in find_pickling_error
    raise Exception(msg)
Exception: I could not find the exact pickling error.
```

Any ideas? If you don't have the time to investigate and have no ideas off of the top of your head, don't worry about it too much. I'm just glad you've provided some general guidelines as to how your code should work!

**Comment by AndreaCensi** [comment]
Hi Sean,

I can see what's the problem --- it is a bug.

Here's the workaround: I see that you have downloaded using `wget` and now the file is in a directory `censi.mit.edu/.../`. Try to move the log file in the current directory.

**Comment by AndreaCensi** [comment]
Ok, I committed a fix for `aer_video`. Can you see if the error goes away?

**Comment by AndreaCensi** [comment]
Now `aer_blink_detect` should be fixed as well.

**Comment by Seanny123** [comment]
I now get a new error:

```
WARNING:quickapp:No description at all for <class 'aer.programs.video.app.AERVideoApp'>
/home/sean/CNRG/env_dvs-master/src/quickapp/src/decent_params/decent_params_imp.py:138: UserWarning: Not sure below
  warnings.warn('Not sure below')
WARNING:video:PyContracts disabled for speed. Use --contracts to activate.
INFO:contracts:All contracts checking disabled.
/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app.py:112: UserWarning: removed configuration below
  warnings.warn('removed configuration below')  # (start)
quickapp using db tmp-videos/tmp/compmake
/home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/compmake_context.py:187: UserWarning: add prefix to report manager
  warnings.warn('add prefix to report manager')
INFO:compmake:Cleaning job: 'aereventsshowsimple-1212DVSdata/data/dec10/flying/l11.aedat-0.03-aer_video_meat' (defined by ['root'])
___ aereventsshowsimple-0-0.03-aer_video_meat _______________________________________________________________________________
procgraph:Could not import CV                                                                                                
/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_statistics/covariance2.py:6: UserWarning: remove below dipendence 
on boot_agents                                                                                                               
  warnings.warn('remove below dipendence on boot_agents')                                                                    
aer:Reading from example_data/censi.mit.edu/pub/1212-DVS-data/data/dec10/flying/l11.aedat                                    
aer:Reading 10984005 events...                                                                                               
aer:... done                                                                                                                 
pg: >mencoder:Writing 512x512 rgb24 video stream at 30.000 fps to 'example_data/censi.mit.edu/pub/1212-DVS-data/data/dec     
10/flying/l11.aedat.show_simple-0.03.mp4'.                                                                                   
pg: Execution of M:aer_events_show_simple:cmdline(in:/;out:/) failed: User-thrown exception while calling update() in bl     
ock 'mencoder'.                                                                                                              
pg: - B:MEncoder:mencoder(in:image;out:/) 140538556420688                                                                    
pg: - M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352                                                           
pg: > Traceback (most recent call last):                                                                                     
pg: >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update                 
pg: >     result = block.update()                                                                                            
pg: >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update            
pg: >     self.try_initialization()                                                                                          
pg: >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initiali     
zation                                                                                                                       
pg: >     stderr=self.tmp_stderr.fileno())                                                                                   
pg: >   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                       
pg: >     errread, errwrite)                                                                                                 
pg: >   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child                                                
pg: >     raise child_exception                                                                                              
pg: > OSError: [Errno 2] No such file or directory                                                                           
pg: >                                                                                                                        
pg: I will attempt clean-up.                                                                                                 
Job 'aereventsshowsimple-0-0.03-aer_video_meat' failed on host 'localhost': User-thrown exception while calling update() in block 'mencoder'.
- B:MEncoder:mencoder(in:image;out:/) 140538556420688                                                                        
- M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352                                                               
> Traceback (most recent call last):                                                                                         
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update                     
>     result = block.update()                                                                                                
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update                
>     self.try_initialization()                                                                                              
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initialization   
>     stderr=self.tmp_stderr.fileno())                                                                                       
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                           
>     errread, errwrite)                                                                                                     
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child                                                    
>     raise child_exception                                                                                                  
> OSError: [Errno 2] No such file or directory                                                                               
>                                                                                                                            
Traceback (most recent call last):                                                                                           
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/jobs/actions.py", line 170, in make                         
    result = computation.compute(context=context)                                                                            
  File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/structures.py", line 176, in compute                        
    res = command(*args, **kwargs)                                                                                           
  File "/home/sean/CNRG/env_dvs-master/src/rcl/src/aer/programs/video/app.py", line 38, in aer_video_meat                    
    pg(model, config)                                                                                                        
  File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/scripts/pgmain.py", line 234, in pg                       
    raise e                                                                                                                  
BadMethodCall: User-thrown exception while calling update() in block 'mencoder'.                                             
- B:MEncoder:mencoder(in:image;out:/) 140538556420688                                                                        
- M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352                                                               
> Traceback (most recent call last):                                                                                         
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update                     
>     result = block.update()                                                                                                
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update                
>     self.try_initialization()                                                                                              
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initialization   
>     stderr=self.tmp_stderr.fileno())                                                                                       
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                           
>     errread, errwrite)                                                                                                     
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child                                                    
>     raise child_exception                                                                                                  
> OSError: [Errno 2] No such file or directory                                                                               
>                                                                                                                            
Job 'aereventsshowsimple-0-0.03-aer_video_meat' failed: User-thrown exception while calling update() in block 'mencoder'.    
- B:MEncoder:mencoder(in:image;out:/) 140538556420688                                                                        
- M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352                                                               
> Traceback (most recent call last):                                                                                         
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update                     
>     result = block.update()                                                                                                
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update                
>     self.try_initialization()                                                                                              
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initialization   
>     stderr=self.tmp_stderr.fileno())                                                                                       
>   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__                                                           
>     errread, errwrite)                                                                                                     
>   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child                                                    
>     raise child_exception                                                                                                  
> OSError: [Errno 2] No such file or directory                                                                               
>                                                                                                                            
Command 'make' failed: 1 job(s) failed. 
```

Once again, don't worry if you don't have time to resolve this. Just digging into your code is good enough for me.

**Comment by AndreaCensi** [comment]
Try installing the packages mplayer and ffmpeg.

On Monday, May 19, 2014, Sean Aubin notifications@github.com wrote:

> I now get a new error:
> 
> WARNING:quickapp:No description at all for <class 'aer.programs.video.app.AERVideoApp'>
> /home/sean/CNRG/env_dvs-master/src/quickapp/src/decent_params/decent_params_imp.py:138: UserWarning: Not sure below
>   warnings.warn('Not sure below')
> WARNING:video:PyContracts disabled for speed. Use --contracts to activate.
> INFO:contracts:All contracts checking disabled.
> /home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/quick_app.py:112: UserWarning: removed configuration below
>   warnings.warn('removed configuration below')  # (start)
> quickapp using db tmp-videos/tmp/compmake
> /home/sean/CNRG/env_dvs-master/src/quickapp/src/quickapp/compmake_context.py:187: UserWarning: add prefix to report manager
>   warnings.warn('add prefix to report manager')
> INFO:compmake:Cleaning job: 'aereventsshowsimple-1212DVSdata/data/dec10/flying/l11.aedat-0.03-aer_video_meat' (defined by ['root'])
> ___ aereventsshowsimple-0-0.03-aer_video_meat _______________________________________________________________________________
> procgraph:Could not import CV
> /home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_statistics/covariance2.py:6: UserWarning: remove below dipendence
> on boot_agents
>   warnings.warn('remove below dipendence on boot_agents')
> aer:Reading from example_data/censi.mit.edu/pub/1212-DVS-data/data/dec10/flying/l11.aedat
> aer:Reading 10984005 events...
> aer:... done
> pg: >mencoder:Writing 512x512 rgb24 video stream at 30.000 fps to 'example_data/censi.mit.edu/pub/1212-DVS-data/data/dec
> 10/flying/l11.aedat.show_simple-0.03.mp4'.
> pg: Execution of M:aer_events_show_simple:cmdline(in:/;out:/) failed: User-thrown exception while calling update() in bl
> ock 'mencoder'.
> pg: - B:MEncoder:mencoder(in:image;out:/) 140538556420688
> pg: - M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352
> pg: > Traceback (most recent call last):
> pg: >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update
> pg: >     result = block.update()
> pg: >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update
> pg: >     self.try_initialization()
> pg: >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initiali
> zation
> pg: >     stderr=self.tmp_stderr.fileno())
> pg: >   File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
> pg: >     errread, errwrite)
> pg: >   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
> pg: >     raise child_exception
> pg: > OSError: [Errno 2] No such file or directory
> pg: >
> pg: I will attempt clean-up.
> Job 'aereventsshowsimple-0-0.03-aer_video_meat' failed on host 'localhost': User-thrown exception while calling update() in block 'mencoder'.
> - B:MEncoder:mencoder(in:image;out:/) 140538556420688
> - M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352
>   > Traceback (most recent call last):
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update
>   >     result = block.update()
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update
>   >     self.try_initialization()
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initialization
>   >     stderr=self.tmp_stderr.fileno())
>   >   File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
>   >     errread, errwrite)
>   >   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>   >     raise child_exception
>   > OSError: [Errno 2] No such file or directory
>   >
>   Traceback (most recent call last):
>   File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/jobs/actions.py", line 170, in make
>     result = computation.compute(context=context)
>   File "/home/sean/CNRG/env_dvs-master/src/compmake/src/compmake/structures.py", line 176, in compute
>     res = command(_args, *_kwargs)
>   File "/home/sean/CNRG/env_dvs-master/src/rcl/src/aer/programs/video/app.py", line 38, in aer_video_meat
>     pg(model, config)
>   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/scripts/pgmain.py", line 234, in pg
>     raise e
>   BadMethodCall: User-thrown exception while calling update() in block 'mencoder'.
> - B:MEncoder:mencoder(in:image;out:/) 140538556420688
> - M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352
>   > Traceback (most recent call last):
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update
>   >     result = block.update()
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update
>   >     self.try_initialization()
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initialization
>   >     stderr=self.tmp_stderr.fileno())
>   >   File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
>   >     errread, errwrite)
>   >   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>   >     raise child_exception
>   > OSError: [Errno 2] No such file or directory
>   >
>   Job 'aereventsshowsimple-0-0.03-aer_video_meat' failed: User-thrown exception while calling update() in block 'mencoder'.
> - B:MEncoder:mencoder(in:image;out:/) 140538556420688
> - M:aer_events_show_simple:cmdline(in:/;out:/) 140538564342352
>   > Traceback (most recent call last):
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph/core/model.py", line 302, in update
>   >     result = block.update()
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 83, in update
>   >     self.try_initialization()
>   >   File "/home/sean/CNRG/env_dvs-master/src/procgraph/src/procgraph_mplayer/mencoder.py", line 201, in try_initialization
>   >     stderr=self.tmp_stderr.fileno())
>   >   File "/usr/lib/python2.7/subprocess.py", line 710, in **init**
>   >     errread, errwrite)
>   >   File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
>   >     raise child_exception
>   > OSError: [Errno 2] No such file or directory
>   >
>   Command 'make' failed: 1 job(s) failed.
> 
> Once again, don't worry if you don't have time to resolve this. Just
> digging into your code is good enough for me.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/AndreaCensi/env_dvs/issues/3#issuecomment-43575642
> .

## 

(sent from mobile device, please pardon typos and brevity)

**Comment by Seanny123** [comment]
`mencoder` was the dependency I was missing. Sorry about that, I really should have been able to figure that out for myself based off the error. I'll read a little more carefully next time.

**Comment by AndreaCensi** [comment]
No problem, don't hesitate to signal if you're stuck or things are unclear.
